version: '3.0'
services:
  webapp:
    image: weather/webapp:local
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      # Speed up local development
      - "./frontend/public/:/usr/src/app/public/"
      - "./frontend/src/:/usr/src/app/src/"
      - "./frontend/.env:/usr/src/app/.env"

  api:
    depends_on:
      - db
    image: weather/api:local
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_NAME: weather_db
      DB_USER: weather_user
      DB_PASSWORD: weather_pass
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      # Speed up local development
      - "./backend/:/usr/src/app/"

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_db